### ISSUE TITLE
[Framework] Update the Domains page to align with Framework v1 information architecture 

### ISSUE THREAD

**Issue by vnm-fodo** [finopsfoundation/framework#204]
update to the current Framework Domains page to leverage the Framework v1 Domain structure and content via an inline "cards" layout.

v1 Framework content+layout for the Domain "cards" is staged in the doc here:
https://docs.google.com/document/d/1-WKwkANU-VG430rR9VV5wIXXj21OWU0pYqQY1ZqsvhQ

 tables were used to represent the individual Domain cards

**Comment by stevetrask** [comment]
Pushed live with #212
