### ISSUE TITLE
[Vendor] Update the "Supported Functions" section title to "Supported Capabilities" for the vendor member intake form 

### ISSUE THREAD

**Issue by vnm-fodo** [finopsfoundation/framework#205]
the current vendor member intake form has a section called "Supported Functions" which should be updated to "Supported Capabilities" to align with the Framework v1.

see example pic here: https://share.getcloudapp.com/qGuJDN6b

vendor member intake form is here:
https://docs.google.com/forms/d/e/1FAIpQLSdNB6xHr_xxkWwFJnYX-bEbWIxogm4D1wQzieISuKSn2gQ-Fg/viewform

**Comment by stevetrask** [comment]
I have made the update :)
