### ISSUE TITLE
[Vendor] Update the vendor member intake form to add a new section for "Supported Domains"

### ISSUE THREAD

**Issue by vnm-fodo** [finopsfoundation/framework#206]
add a new section called "Supported Domains" above the existing "Supported Capabilities" section in the form to enable vendor member applicants to self-select from a list of Framework v1 Domains

list of Framework Domains  for the new in-take form section:
- Understanding Cloud Usage & Cost
- Performance Tracking & Benchmarking
- Real-Time Decision Making
- Cloud Rate Optimization
- Cloud Usage Optimization
- Organizational Alignment

member intake form is here:
https://docs.google.com/forms/d/e/1FAIpQLSdNB6xHr_xxkWwFJnYX-bEbWIxogm4D1wQzieISuKSn2gQ-Fg/viewform

**Comment by stevetrask** [comment]
As discussed with @vnm-fodo we can gain these by determining it from the capabilities, this removes the broader approach and allows us to be more precise.
