### ISSUE TITLE
Add contributors to each page so framework.finops.org displays who worked on a page

### ISSUE THREAD

**Issue by jrstorment** [finopsfoundation/framework#21]
Can we use something like this https://allcontributors.org/docs/en/bot/overview to add contributors to each markdown?

**Comment by stevetrask** [comment]
https://github.com/thodorisbais/markdown-contributors adding for reference, we need to do some discovery if we can do per file or if it is just per repo

**Comment by stevetrask** [comment]
Looking for a non GH solution
