### ISSUE TITLE
[Framework] update Domain card ordering on main Domains page to align with FinOps infographic/poster

### ISSUE THREAD

**Issue by vnm-fodo** [finopsfoundation/framework#217]
currently when the domain cards are layed-out in alphabetical ordering on the main Domains page; we should update the ordering to [align with the how domains are ordered on FinOps infographic/poster](https://finopsfoundation.slack.com/files/UQ40T5GKB/F02B6H8V6LT/finops_poster_-_draft_v3.pdf).

card layout ordering should be:
0.Understanding Cloud Usage & Cost
1.Performance Tracking & Benchmarking
2.Real-Time Decision Making
3.Cloud Rate Optimization
4.Cloud Usage Optimization
5.Organizational Alignment

**Comment by stevetrask** [comment]
Pushed with #212
