### ISSUE TITLE
[Framework] Update Personas page to align with FinOps infographic/poster personas

### ISSUE THREAD

**Issue by vnm-fodo** [finopsfoundation/framework#218]
currently[ the fodo Personas page ](https://www.finops.org/framework/personas/)includes a "FinOps Practioner" 
(see pic here: https://share.getcloudapp.com/P8uGE480)

let's update the Personas to align with 
1. the FinOps poster "stakeholders" 
(see pic here: https://share.getcloudapp.com/5zuN1zmq)

2. also to align with the FinOps operating model team structure 
(see pic here: https://share.getcloudapp.com/4gulygAy)

**Comment by stevetrask** [comment]
I have pushed a quick change to the title and content adjustment for the FinOps Practitioner, I will loop back and to do the team structure
