### ISSUE TITLE
[Framework] re-evaluate and update Framework Principles

### ISSUE THREAD

**Issue by vnm-fodo** [finopsfoundation/framework#237]
a suggestion to re-evaluate and update the current FinOps Principles came out of [a recent TAC brainstorming session](https://easyretro.io/publicboard/fLEWqAyHDLUBIkKeSs2PhkGCwNE3/877eef85-e322-4f69-a732-022e8142df3d)

it's worth mentioning that updating the FinOps principles is out-of-scope for the WiP wrt Framework v1;  adding this ticket to the backlog to revisit this request during the next Framework rev.

**Comment by stevetrask** [comment]
Just to add to this item that the poster would require an update if the principles are updated, so we need to be mindful of communicating the timeline to vendor members if they are already using this in any activities.

**Comment by vnm-fodo** [comment]
great call-out here Steve - thanks for posting that additional color 👍

**Comment by andrewnhem** [comment]
Super old and looks like this was resolved offline. Closing!

**Comment by vnm-fodo** [comment]
for context - i created this ticket as a placeholder for my backlog with the thinking that - at some point in the future - we would need to revisit and review Framework elements for possible updates/refresh.  i've received feedback that Principles are a good candidate once we get Maturity sorted.
