### ISSUE TITLE
Revisit F2 homepage (to address onboarding/UX)

### ISSUE THREAD

**Issue by andrewnhem** [finopsfoundation/framework#329]
We discussed some homepage constructs at one point in early 2021 ([like this for example](https://docs.google.com/document/d/1U-k1wr6Qp-GBAIIT4qN7snMIS48H8Uv8DWv2hZaL3zw/edit)). We should take a look at whether or not we still want to do this.

It seems like it's in our best interest as discussion topics re: onboarding, what new users should do, and our page ranking tend to pop up here and there.

**Comment by stevetrask** [comment]
Moved to Monday
