### ISSUE TITLE
Add a "WG" status overview to each challenge

### ISSUE THREAD

**Issue by jrstorment** [finopsfoundation/framework#41]
We should have a standardized header for each challenge that shows the status of the project, who contributed (chairs, TAC, AND individual members), etc for each WG (past - present - future. This could be indicated by a 'sandbox, incubating, graduated, etc' nomenclature. I added some ideas to each of them but eng status still needs one too.

Example:
Playbook Details
Status: Graduated
Slack room: https://finopsfoundation.slack.com/archives/C0180PC67T2
SIG Ownership: Kubernetes
Chairperson:
TAC Liaison: Eugene Khvostov

**Comment by stevetrask** [comment]
Closing due to age and new website changes - content changes should now be added to Monday
