### ISSUE TITLE
[finops resources] Website Contribution for the Reducing Waste Project

### ISSUE THREAD

**Issue by stevetrask** [finopsfoundation/framework#521]
https://finopsfoundation.slack.com/archives/C029SCMA50B/p1647532298476019?thread_ts=1647515389.393039&cid=C029SCMA50B

Andy Foley pointed this link to help with Azure VM start/stops

Submitted on: https://www.finops.org/projects/reducing-waste/

**Comment by stevetrask** [comment]
@vnm-fodo I am not sure exactly how this should be added in the reducing waste format inc meta data

**Comment by vnm-fodo** [comment]
no worries @stevetrask  - i'll take a peek at getting it added 👍
