### ISSUE TITLE
[framework] Website Contribution for Managing Anomalies  Framework Capability

### ISSUE THREAD

**Issue by stevetrask** [finopsfoundation/framework#567]
**Add under KPI section**

For actioned anomalies, spend avoided calculated to nearest billing period
number of alerts suspended (ignored), will help measure how well your process is working and identify regular 'ignore offenders'
Capture justification of ignore, help increase triage or further eduction plans

Submitted on: https://www.finops.org/framework/capabilities/manage-anomalies/

**Comment by stevetrask** [comment]
@vnm-fodo can you review the suggestion?

**Comment by vnm-fodo** [comment]
oh yah ...this is a great suggestion - thx @stevetrask  - i will add it to the Capability.  any chance you have contact information for this contribution ?

**Comment by andrewnhem** [comment]
Closing here as it's being reviewed for new site via Ashley
