### ISSUE TITLE
[framework] Website Contribution for Establishing a FinOps Decision & Accountability Structure Framework Capability

### ISSUE THREAD

**Issue by stevetrask** [finopsfoundation/framework#585]
Establishing a FinOps Decision & Accountability Structure

Definition

Establishing a clear FinOps Decision and Accountability Structure, such as a management team, committee, or working group, provides direction while nurturing equity and inclusivity to resolve actual or perceived power imbalances that can arise during financial decision making and collaboration. This structure should include clear lines of authority and guidelines, enabling issues to be escalated and resolved, and giving senior decision-makers the opportunity to make informed decisions quickly and in a consistent manner.

Try to use existing decision making and governance mechanisms. Ensure the FinOps Decision and Accountability structure is clear and documented, including who has decision making authority versus who has an advisory role. Work out how your team structure connects to the broader governance arrangements of your agency to ensure clear reporting lines and accountability for tasks and deliverables.

Maturity Assessment

Crawl
Simple hierarchy of decision making authority and accountability.
Limited documentation of the Decision and Accountability structure and processes.
Few controls to assist with strategy or development of a consistent approach.

Walk
Clearly defined hierarchy of decision making authority and accountability.
Decision and Accountability structure and processes are well documented, and have become standard.
Management is involved with implementing and supporting these procedures and standards.
Regular use and review of FinOps metrics to help with decision making and planning.
Well defined relationships and processes allow for strategic planning and for the organization to react and make decisions quickly and in a consistent manner.

Run
Clear and well documented FinOps Decision and Accountability Structure relationships and processes.
Regular standardized FinOps decision making processes in place, utilizing agreed FinOps metrics.
Management can review current analytics and decide whether or not to make strategic changes.
FinOps decisions and processes are compared and benchmarked against other organizations.
Processes are in place to continuously review and improve the FinOps Decision and Accountability Structure and performance.

Submitted on: https://www.finops.org/framework/capabilities/decision-accountability-structure

**Comment by vnm-fodo** [comment]
heya @stevetrask  - this is a solid contribution - i'm going to review it and look to add it to the Capability.  any chance you have contact details for the person that submitted this content?

**Comment by vnm-fodo** [comment]
fyi related to #390
