### ISSUE TITLE
Add "Framework Assessment" content / section to FODO

### ISSUE THREAD

**Issue by bendemora** [finopsfoundation/framework#596]
There is a growing wealth of material concerning the Capability Framework Assessment approach (included in the new edition of the book too) that ought to be incorporated into FODO.

Definition documentation / copy text to incorporate: https://github.com/finopsfoundation/frameworkassessment/blob/main/Definition.md

Guide slideshow content: https://docs.google.com/presentation/d/1E_gQrIM49BRv32Az0FjRGM_pbepgenFdio3MSAdiOzQ/edit#slide=id.g11b684fc68b_1_535

**Comment by stevetrask** [comment]
fixed on #642
